name: react-ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/react-app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/react-app/package-lock.json

      # one command that works whether or not you have a lockfile
      - run: npm i

      # run tests if you have them (no-op if not)
      - run: npm run test --if-present --silent
        env:
          CI: true

      - run: npm run build

      # optional: upload CRA (build) or Vite (dist) output if present
      - uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: |
            src/react-app/build
            src/react-app/dist
          if-no-files-found: ignore
